- п
ph1l74/CheckCheck pull request #1
Opened 2017-06-21 13:20 UTC by ph1l74

+ CR

2017-06-22 09:00 UTC, b0g3r requested changes

2017-06-22 09:00 UTC, b0g3r commented on mail.py
> +from io import BytesIO as bio
`bio` - bad, as не нужен здесь

2017-06-22 09:00 UTC, b0g3r commented on mail.py
> +    imap_session = imaplib.IMAP4_SSL(imap_server)
дублирование кода, нужно чет придумать с этим

2017-06-22 09:00 UTC, b0g3r commented on main.py
> +    print("    {}".format(file[0]))
эт че за таб в начале)

2017-06-22 10:23 UTC, b0g3r requested changes

2017-06-22 10:23 UTC, b0g3r commented on config.py
> +_Imap = collections.namedtuple('_Imap', ['server', 'user', 'password'])
большими

2017-06-22 10:23 UTC, b0g3r commented on config.py
> +_Smtp = collections.namedtuple('_Smtp', ['server', 'port', 'user', 'password', 'sender'])
большими

2017-06-22 10:23 UTC, b0g3r commented on config.py
> +imap = _Imap(server=os.environ['IMAP_HOST'],
большими по желанию

2017-06-22 10:23 UTC, b0g3r commented on config.py
> +smtp = _Smtp(server=os.environ['SMTP_HOST'],
большими по желанию

2017-06-22 10:23 UTC, b0g3r commented on mail.py
> +    return True
а когда оно не вернет тру?)

2017-06-22 10:23 UTC, b0g3r commented on mail.py
> +    mail.quit()
ну тут точно контекст-менеджер нужен

2017-06-22 10:23 UTC, b0g3r commented on main.py
> +reciever = ['astakhovfilat@gmail.com']
recievers*

2017-06-22 10:23 UTC, b0g3r commented on mail.py
> +from io import BytesIO as bio
всё ещё `as bio` - зачем?

2017-06-22 10:44 UTC, b0g3r requested changes

2017-06-22 10:44 UTC, b0g3r commented on config.py
> +_IMAP = collections.namedtuple('_Imap', ['server', 'user', 'password'])
первый аргумент

2017-06-22 10:44 UTC, b0g3r commented on config.py
> +_SMTP = collections.namedtuple('_Smtp', ['server', 'port', 'user', 'password', 'sender'])
и тут

2017-06-22 10:44 UTC, b0g3r commented on mail.py
> +def get_mail_files(message_parts, files):
ты зачем files передаешь О_О

2017-06-22 10:44 UTC, b0g3r commented on mail.py
> +    if mode == 'ALL':
это че такое

2017-06-22 10:44 UTC, b0g3r commented on mail.py
> +def send_mail(smtp_host, smtp_port, smtp_user, smtp_password,  smtp_sender, smtp_recievers, mail_message):
без return True в main.py if всегда будет возвращать "not send"

2017-06-22 11:05 UTC, ph1l74 commented on mail.py
> +def send_mail(smtp_host, smtp_port, smtp_user, smtp_password,  smtp_sender, smtp_recievers, mail_message):
Предложения?
Дописать функцию посылки?

2017-06-22 11:05 UTC, ph1l74 commented on mail.py
> +    if mode == 'ALL':
Это ужас. Исправлено.

2017-06-22 14:49 UTC, b0g3r requested changes

2017-06-22 14:49 UTC, b0g3r commented on mail.py
> +def send_mail(smtp_host, smtp_port, smtp_user, smtp_password,  smtp_sender, smtp_recievers, mail_message):
либо убрать if в main'е
либо ловить здесь эксепшены и возвращать фолс если они есть (плохой вариант)

2017-06-22 14:49 UTC, b0g3r commented on mail.py
> +def send_mail(smtp_host, smtp_port, smtp_user, smtp_password,  smtp_sender, smtp_recievers, mail_message):
ну и не очень понятно зачем сюда передаются значения из конфига, пусть сюда конфиг импортируется и берется из него, чем 10 аргументов

2017-06-22 14:49 UTC, b0g3r commented on main.py
> +                  config.smtp.sender, recievers, mail.messages['not found'])
`mail.messages['not found']` - это эпично) оно ж там есть, зачем ты это отсюда туда передаешь)

2017-06-23 12:59 UTC, b0g3r requested changes

2017-06-23 12:59 UTC, b0g3r commented on db.py
> +def reciept_add(id, number, date_payed, date_added):
это должен быть метод в Receipt

2017-06-23 12:59 UTC, b0g3r commented on ocr.py
> +    image_object = Image.open(BytesIO(image_data))
image[0][1] - уже BytesIO
ты перегоняешь из пустого в порожнее:
image[0][1] - BytesIO
image[0][1].read() - bytes
BytesIO(image[0][1].read()) - BytesIO

2017-06-23 12:59 UTC, b0g3r commented on ocr.py
> +def image_to_text(image):
написано image а на вход прилетает images

2017-06-23 12:59 UTC, b0g3r commented on main.py
> +image = mail.get_last_attachment(config.imap.server, config.imap.user, config.imap.password)
написано attachment, а возвращает attachments

2017-06-23 12:59 UTC, b0g3r commented on db.py
> +    number = Column(String)
все ещё не нравится

2017-06-23 12:59 UTC, b0g3r commented on db.py
> +Base.metadata.create_all(engine)
у тебя база создается при каждом импорте db

2017-06-26 08:11 UTC, ph1l74 commented on db.py
> +Base.metadata.create_all(engine)
Я не знаю, что с этим делать :/

2017-06-26 08:38 UTC, b0g3r commented on db.py
> +Base.metadata.create_all(engine)
вынести в отдельный модуль (аля init.py)
обернуть в if main

2017-06-29 19:10 UTC, b0g3r requested changes

2017-06-29 19:10 UTC, b0g3r commented on main.py
> +def Check():
тебе пайчарм не кричит что ты функцию с большой назвал?)

2017-06-29 19:10 UTC, b0g3r commented on mail.py
> +    # write all bytes in list
ты записываешь не байты в лист, а file-like объекты

2017-06-29 19:10 UTC, b0g3r commented on mail.py
> +    re_mask = re.compile(r'[a-zA-Z0-9._-]*@[a-zA-Z0-9._-]*')
1. re.compile внутри блока кода, в котором он используется не имеет смысла: compile используется для часто-используемых регулярок и должен делаться, например, один раз на модуль, т.е. есть смысл поднять его куда-нибудь сильно выше в коде.
2. проверять емейлы регуляркой не нужно. Вот как на самом деле выглядит правильная регулярка для емейлов: http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html. Твоя регулярка покрывает 99% случаев, но нет, спецификация емейла позволяет творить лютейшую херню
Лучше научиться как-нибудь по-другому вытаскивать мыло, без регулярки.

2017-06-29 19:10 UTC, b0g3r commented on mail.py
> +def get_attachments(imap_object, count=1):
опять зачем-то передается конфиг. пусть в этом модуле он импортится и используется, а не передается в функцию. Нужна ли тебе такая сильная модульность и переиспользование?

2017-06-29 19:10 UTC, b0g3r commented on mail.py
> +    return "Mail sent"
Зачем это?

2017-06-29 19:10 UTC, b0g3r commented on main.py
> +
не хватает докстринга или нормального названия функции. пока что это функция, которая проверяет один раз :)

2017-06-29 19:10 UTC, b0g3r commented on main.py
> +    if attachments:
не нужен, если attachments - пустой список, то for просто не выполнится ни разу

2017-06-29 19:11 UTC, b0g3r commented
Сделал ревью, но хотелось бы напомнить о сути и цели PR. Давай либо менять цель PR и ставить какую-нибудь другую, либо возвращаться к этой и делать её. Скоро код слишком разрастется и мне будет сложно его ревьюить

2017-07-06 10:34 UTC, b0g3r approved these changes

2017-07-06 10:34 UTC, merged